package com.grom.domain.dao;

import com.grom.domain.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jlg_user
     *
     * @mbg.generated Tue May 14 09:45:01 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jlg_user
     *
     * @mbg.generated Tue May 14 09:45:01 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jlg_user
     *
     * @mbg.generated Tue May 14 09:45:01 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jlg_user
     *
     * @mbg.generated Tue May 14 09:45:01 CST 2019
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jlg_user
     *
     * @mbg.generated Tue May 14 09:45:01 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jlg_user
     *
     * @mbg.generated Tue May 14 09:45:01 CST 2019
     */
    int updateByPrimaryKey(User record);
}