
spring:
  thymeleaf:
    prefix: classpath:/template/
  application:
    name: server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: default
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/jlg?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  resources:
    static-locations: file:/D:/upload/




  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true


jasper:
  templatePath: /jasper

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

mybatis:
  basepackage: com.grom.domain
  xmlLocation: classpath:com/grom/domain/**/*.xml
  mapper-locations: "classpath:com/grom/domain/**/*.xml"

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#  工作流配置
flowable:
  #关闭定时任务JOB
  async-executor-activate: false


server:
  port: ${INSTANCE_PORT:8081}


# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


# 配置swagger api访问地址http://localhost:8762/swagger-ui.html
swagger:
  enabled: true
  base-package: com.grom.server
  title: server
  version: 1.0.0.SNAPSHOT
  description: 管理后端服务
  contact:
    name: server

auth:
  serviceId: auth-server
  user:
    token-header: Authorization
  client:
    id: server
    secret: 123456
    token-header: x-client-token

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

ftp:
  ip: ${FTP_HOST:127.0.0.1}
  port: 21
  user: ${FTP_USER:root}
  pwd: ${FTP_PASSWORD:123456}
  path: /mftp/img  #tomcat访问的映射路径
  tomcatPort: ${FTP_TOMCAT_PORT:8080}



#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: ${REDIS_HOST:127.0.0.1}
  port: ${REDIS_PORT:6379}

  password:
  timeout: 2000
  # 服务或应用名
  sysName: server
  enable: true
  database: 0

